// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from './client/index.js';
import type { GetMeData, GetMeResponses, GetMeErrors, GetWebhooksData, GetWebhooksResponses, GetWebhooksErrors, CreateWebhookData, CreateWebhookResponses, CreateWebhookErrors, DeleteWebhookData, DeleteWebhookResponses, DeleteWebhookErrors, UpdateWebhookData, UpdateWebhookResponses, UpdateWebhookErrors, CreateTokenViaAuthorizationCodeData, CreateTokenViaAuthorizationCodeResponses, PostProductViewEventsData, PostProductViewEventsResponses, PostProductViewEventsErrors, PostAddToCartEventsData, PostAddToCartEventsResponses, PostAddToCartEventsErrors, PostPurchaseEventsData, PostPurchaseEventsResponses, PostPurchaseEventsErrors, CreateCouponsData, CreateCouponsResponses, CreateCouponsErrors, GetUsersData, GetUsersResponses, GetUsersErrors, PostCustomEventsData, PostCustomEventsResponses, PostCustomEventsErrors, GetCustomAttributesData, GetCustomAttributesResponses, GetCustomAttributesErrors, PostCustomAttributesData, PostCustomAttributesResponses, PostCustomAttributesErrors, GetSubscriptionsData, GetSubscriptionsResponses, GetSubscriptionsErrors, AddSubscriptionsData, AddSubscriptionsResponses, AddSubscriptionsErrors, UnsubscribeSubscriptionsData, UnsubscribeSubscriptionsResponses, UnsubscribeSubscriptionsErrors, GetUploadsData, GetUploadsResponses, GetUploadsErrors, PostUploadData, PostUploadResponses, PostUploadErrors, LookupUploadData, LookupUploadResponses, LookupUploadErrors, AddDeleteRequestData, AddDeleteRequestResponses, AddDeleteRequestErrors, GetDeleteRequestData, GetDeleteRequestResponses, GetDeleteRequestErrors, IdentifyData, IdentifyResponses, IdentifyErrors } from './types.gen.js';
import { client as _heyApiClient } from './client.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Me
 * Make a call to this endpoint to test your unique token that you generate in the Attentive product.
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMeResponses, GetMeErrors, ThrowOnError>({
        url: '/me',
        ...options
    });
};

/**
 * List webhooks
 * Make an API call to this endpoint to list existing webhooks.
 */
export const getWebhooks = <ThrowOnError extends boolean = false>(options?: Options<GetWebhooksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetWebhooksResponses, GetWebhooksErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/webhooks',
        ...options
    });
};

/**
 * Create webhook
 * Make an API call to this endpoint to subscribe to a webhook.
 *
 * Events are a collection of strings of the following types:
 * * `sms.subscribed`
 * * `sms.sent`
 * * `sms.message_link_click`
 * * `email.subscribed`
 * * `email.unsubscribed`
 * * `email.message_link_click`
 * * `email.opened`
 * * `custom_attribute.set`
 *
 * Event types are case sensitive.
 *
 * All events included will be sent to the URL.
 *
 */
export const createWebhook = <ThrowOnError extends boolean = false>(options: Options<CreateWebhookData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateWebhookResponses, CreateWebhookErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/webhooks',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete webhook
 * Make an API call to this endpoint to remove a webhook.
 */
export const deleteWebhook = <ThrowOnError extends boolean = false>(options: Options<DeleteWebhookData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteWebhookResponses, DeleteWebhookErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/webhooks/{webhookId}',
        ...options
    });
};

/**
 * Update webhook
 * Make an API call to this endpoint to update a webhook
 */
export const updateWebhook = <ThrowOnError extends boolean = false>(options: Options<UpdateWebhookData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateWebhookResponses, UpdateWebhookErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/webhooks/{webhookId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Access Token
 * Make a call to this endpoint to exchange a temporary authorization code for an access token.
 */
export const createTokenViaAuthorizationCode = <ThrowOnError extends boolean = false>(options?: Options<CreateTokenViaAuthorizationCodeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateTokenViaAuthorizationCodeResponses, unknown, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/authorization-codes/tokens',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Product view
 * Make a call to this endpoint when a user views a product.
 */
export const postProductViewEvents = <ThrowOnError extends boolean = false>(options: Options<PostProductViewEventsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostProductViewEventsResponses, PostProductViewEventsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/events/ecommerce/product-view',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Add to cart
 * Make a call to this endpoint when a user adds a product to their shopping cart.
 */
export const postAddToCartEvents = <ThrowOnError extends boolean = false>(options: Options<PostAddToCartEventsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostAddToCartEventsResponses, PostAddToCartEventsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/events/ecommerce/add-to-cart',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Purchase
 * Make a call to this endpoint when a user generates an order or purchase.
 */
export const postPurchaseEvents = <ThrowOnError extends boolean = false>(options: Options<PostPurchaseEventsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostPurchaseEventsResponses, PostPurchaseEventsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/events/ecommerce/purchase',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Add discount codes
 * Note: Once the offer(s) has been created, please reach out to an Attentive team member to enable this API feature for you
 *
 *
 * Make a call to this asynchronous endpoint to create new discount codes in an existing offer.
 */
export const createCoupons = <ThrowOnError extends boolean = false>(options: Options<CreateCouponsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateCouponsResponses, CreateCouponsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/coupons/coupon-pool/{coupon-pool-id}/create',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get bulk User information
 * Provides User data and their corresponding Subscription info
 *
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUsersResponses, GetUsersErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users',
        ...options
    });
};

/**
 * Custom Events
 * Make a call to this endpoint for any event-based data representing user actions.
 */
export const postCustomEvents = <ThrowOnError extends boolean = false>(options: Options<PostCustomEventsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostCustomEventsResponses, PostCustomEventsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/events/custom',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Custom Attributes for a User
 * Make a call to this endpoint to retrieve all custom attribute data associated with a user. You can query this endpoint by either phone or email.
 *
 * **Note: You must include a single query parameter, phone or email. Including both will result in a 400 error.**
 *
 */
export const getCustomAttributes = <ThrowOnError extends boolean = false>(options?: Options<GetCustomAttributesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCustomAttributesResponses, GetCustomAttributesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/attributes/custom',
        ...options
    });
};

/**
 * Custom Attributes
 * Make a call to this endpoint for any attribute-based data. There are no limits to the amount of custom attributes that can be created. Note that you can create net-new properties with this API, however, it cannot be used to create new values for an existing UI-created property name. If a property name is created through the Attentive platform, all possible property values must also be defined in the platform. For example, if a property has possible values of "Adult, Teen, Children's", those are the only values that will be accepted through the API. This does not apply for properties with the type "Custom input", for example: Full Name. Also, please note that the API does not support arrays. For example, attempting to pass an array such as '["chicago", "new york"]' for an attribute like 'favorite_city' will result in a 400 error.
 *
 * **Note : The maximum length for an attribute name is 200 characters.**
 *
 */
export const postCustomAttributes = <ThrowOnError extends boolean = false>(options: Options<PostCustomAttributesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostCustomAttributesResponses, PostCustomAttributesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/attributes/custom',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get subscription eligibility for a user
 * Make a call to this endpoint to list all subscription types and channels a user is subscribed to. You can query for a subscriber using either their phone number or email. One of the query parameters is required in order to look up a subscriber. As an example, you can use this endpoint to check if a subscriber is eligible to receive SMS or email campaigns, and then send them a message based on that eligibility.
 *
 */
export const getSubscriptions = <ThrowOnError extends boolean = false>(options?: Options<GetSubscriptionsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSubscriptionsResponses, GetSubscriptionsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/subscriptions',
        ...options
    });
};

/**
 * Subscribe user
 * Make a call to this endpoint to opt-in a user to a subscription.
 *
 * Notes:
 * - A legal disclosure is required when a user is opted-in programmatically.
 * - For marketing messages, required [legal language](https://docs.attentivemobile.com/pages/legal-docs/legal-disclosure-language/) must be included.
 *
 * - For transactional messages, you must include a [transactional opt-in unit](https://docs.attentivemobile.com/pages/legal-docs/legal-transactional/).
 *
 * - By default, if a subscription already exists, it will try and record the attempt to create the subscription again. For TEXT subscriptions, this will result in a message being sent to the person indicating that they are already subscribed.
 * - Requests to opt-in subscribers must either contain a) a sign-up source id or b) both a locale and a subscription type.
 * - The unique identifier of a sign-up source can be found in the Sign-up Units tab of the Attentive platform in the ID column.
 * If this value is provided in the request, then this sign-up unit will be used for opting in the user in the request.
 *
 * - Callers of this endpoint have the option to omit `signUpSourceId` and, instead, provide both a `locale` and a `subscriptionType` (see below for field details).
 * Given the locale and subscription type, Attentive will resolve any matching API opt-in units. To opt-in a user to a subscription without a `signUpSourceId` and exclusively based on locale and subscription type,
 * there must be exactly one API sign-up unit that matches the provided locale and subscription type. Conversely, requests that contain a locale and a subscription type
 * that do not have a corresponding sign-up unit or that have multiple matching sign-up units will receive a `400` response and will not opt a user into a subscription.
 *
 * - Phone numbers must be submitted in [e164 format](https://en.wikipedia.org/wiki/E.164).
 * - valid examples: `+19148440001`, `+442071838750`, `+551155256325`
 * - invalid examples: `19148440001`, `+1---914---844---0001`, `1 () 914 844 0001`
 *
 */
export const addSubscriptions = <ThrowOnError extends boolean = false>(options: Options<AddSubscriptionsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddSubscriptionsResponses, AddSubscriptionsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/subscriptions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Unsubscribe subscriptions for a user
 * Make a call to this endpoint to unsubscribe a user from a subscription type or channel. If no subscriptions
 * are present in the request, the user is unsubscribed from all subscriptions. If subscriptions are present
 * in the request, the user is unsubscribed from the requested type or channel combination. By default, if a
 * subscription exists, but the user is already unsubscribed, it records the attempt to unsubscribe the
 * subscription again. For TEXT subscriptions, a message is sent to the person indicating that they are
 * unsubscribed.
 *
 * For the user object, the email data point determines which email subscriptions a user has and the phone data point
 * determines which text (or sms) subscriptions a user has. Passing in an email does not locate, nor unsubscribe,
 * a user from any sms subscriptions. Similarly, passing in a phone does not locate, nor unsubscribe, a user from any email subscriptions.
 *
 */
export const unsubscribeSubscriptions = <ThrowOnError extends boolean = false>(options: Options<UnsubscribeSubscriptionsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UnsubscribeSubscriptionsResponses, UnsubscribeSubscriptionsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/subscriptions/unsubscribe',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * View Recent Catalog Uploads
 * Make a call to this endpoint to list recent catalog uploads with their statuses to gain visibility into the ingestion workflow in order of creation. See the POST of this endpoint for details.
 * `Expires` indicates how long you can wait before uploading the product catalog file. If the catalog upload expires, then we will no longer process the file that you upload and you will need to initiate  a new catalog upload.
 *
 */
export const getUploads = <ThrowOnError extends boolean = false>(options?: Options<GetUploadsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUploadsResponses, GetUploadsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/product-catalog/uploads',
        ...options
    });
};

/**
 * Upload Product Catalog
 * Make a call to this endpoint to start sending Attentive your full or partial product catalog.
 * The process starts with a POST to this endpoint, where you will receive a pre-signed AWS S3 URL. You can
 * use any language's http request libraries for uploading a file via HTTP. Here's how to do it with `curl` as an example
 *
 *
 * ```
 * curl --upload-file ${fileNameLocally} ${presignedURL}
 * ```
 *
 *
 * and here's an example in Python
 * ```python
 * import requests
 * with open(filepath, 'rb') as f:
 * r = requests.put(upload_url, data=f)
 * ```
 *
 * [Here are examples from AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html) on how to send the file over in popular programming languages. Note that you aren't interested in
 * the portion of these examples where they are generating the pre-signed URL, but simply the http call to upload the file to the URL.
 *
 * Once your full or partial product catalog begins to upload, the status is updated to
 * `validating` while it's processing and the file is checked for errors. After the upload is
 * validated, the status is updated to `validated`. Once the catalog is saved,
 * the status is updated to `completed`. In cases where there are errors saving
 * the data, Attentive Engineering is notified and will contact you.
 *
 *
 * To ensure there are no validation errors in the file, you can set `validateOnly` parameter
 * to `true` to avoid saving any data. We highly recommend this during your development to get a
 * faster feedback loop on any validation errors as you generate files.
 *
 *
 * If there are no errors returned in the upload response, your product catalog uploaded
 * successfully.
 *
 */
export const postUpload = <ThrowOnError extends boolean = false>(options?: Options<PostUploadData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostUploadResponses, PostUploadErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/product-catalog/uploads',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Lookup Product Catalog Ingestion
 * Making a GET request with the uploadID from your original catalog upload POST will give you the updated information on how the upload is progressing. You can also use the list endpoint as well to retrieve the same data. Please see the POST of `/product-catalog/uploads` for more detail.
 *
 */
export const lookupUpload = <ThrowOnError extends boolean = false>(options: Options<LookupUploadData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<LookupUploadResponses, LookupUploadErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/product-catalog/uploads/{uploadId}',
        ...options
    });
};

/**
 * Add a deletion request
 * Make a call to this endpoint to create a new privacy deletion request. This will delete a subscriber within thirty days, provided the call was successful.
 *
 */
export const addDeleteRequest = <ThrowOnError extends boolean = false>(options: Options<AddDeleteRequestData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddDeleteRequestResponses, AddDeleteRequestErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/privacy/delete-request',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get a CCPA delete request by Id
 */
export const getDeleteRequest = <ThrowOnError extends boolean = false>(options: Options<GetDeleteRequestData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetDeleteRequestResponses, GetDeleteRequestErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/privacy/delete-request/{id}',
        ...options
    });
};

/**
 * Add a client user identifier or custom identifier(s) to a user
 * Make a call to this endpoint to associate a client user identifier or custom identifier(s) with other identifiers. A client user or custom identifier needs to be accompanied by at least one other identifier of the following types: phone, email, shopify id, klaviyo id, client user identifier, or custom identifier.
 *
 */
export const identify = <ThrowOnError extends boolean = false>(options?: Options<IdentifyData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<IdentifyResponses, IdentifyErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/identity-resolution/user-identifiers',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};